version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout-tracker
    ports:
      - "7777:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
